### ISSUE TITLE
`portal-bridge` should be usable by anybody 

### ISSUE THREAD

**Issue by mrferris** [ethereum/trin#1014]
Currently `portal-bridge` can only use nodes from EF "pandaops" as providers via `PANDAOPS` envvar credentials.

My understanding is that these pandaops are geth nodes, so it seems natural that `portal-bridge` should be able to connect to any geth node that a user provides. 

Please comment any extra context/blockers.

**Comment by njgheorghita** [comment]
> My understanding is that these pandaops are geth nodes,

That's not always true. So, this feature will require some kind of logic to recognize the connected client type, and deserialize responses accordingly. Which, iirc wasn't trivial. I'm still in favor of this feature, but just don't think it'll be simple as updating the provider url.

**Comment by mrferris** [comment]
The type of client reached by pandaops as it's currently used by `portal-bridge` can change? How can that be the case if `portal-bridge` doesn't currently contain any logic to recognize client types and deserialize accordingly? Has this caused bridge issues in the past?

**Comment by KolbyML** [comment]
I think what we should do for this is make the provider url configurable then if reports come in of failed deserialization, we will add a patch for that edge case and a unit test to go along with it so we know we don't break the edge case in the future.

I don't think we should worry about what client an end user uses. It isn't a rush to support every edge case as long as it works for us, when new bridge users come we will fix the issues. I don't think we have to fix all the edge cases in one swoop. It will be a gradual process.

**Comment by njgheorghita** [comment]
@mrferris Yeah, for sure it can change. We're currently tied to the archive node, in which case the client doesn't change, which is why we experience consistent behavior. But for a while we were tied to the eu region, which load balances across multiple clients afaik, but you can also tie to a specific client, eg `geth-lighthouse.pandaops.io`. 

So basically, it depends on the padnaops url you choose. And, on top of that, most of the edge cases really don't occur when running in `"latest"` mode. It happens more for historical content, (eg pre-merge / pre-byzantium) afaik.

@KolbyML I agree and disagree. If we approach your suggested ad-hoc method of shipping and fixing deserialization bugs as they are created, it could lead to some very-spaghetti code. Basically patching on patches on patches. In this case, I see some sort of client-detection logic as an inevitability. So the sooner we implement the client-detection logic, the more spaghetti we will be able to avoid. 

Personally, I'm still in the camp that bridge should be for internal use. But, I'll concede that we've had (at least a single instance) of external demand for usage.

Imo the quick & dirty compromise here is to add support for an ***EXPERIMENTAL*** infura url. (Though this should at least be tested to be mostly working in `"latest"` mode) Basically, if you want to use it with infura, cool, you can, but be warned that it might not work 100%, in which case please create an issue. But once we start digging into & resolving the edge cases, I do think it will be better if we implement the client-detection logic and related deserialization asap rather than in a patch-by-patch manner

**Comment by KolbyML** [comment]
> @KolbyML I agree and disagree. If we approach your suggested ad-hoc method of shipping and fixing deserialization bugs as they are created, it could lead to some very-spaghetti code. Basically patching on patches on patches. In this case, I see some sort of client-detection logic as an inevitability. So the sooner we implement the client-detection logic, the more spaghetti we will be able to avoid.

There should only be a few differences in format. So in the deserialization code we can do if x field doesn't exist and y does we know which format it is in.

I don't understand how it would be ``very-spaghetti code``, the code would be contained, instead of being sprawled like an octopus touching everything, passing a client_type variable everywhere, which is what "detecting client type" would do. The deserialization code for Blocks should be a black box imo. All the ``ad-hoc fixes`` would be in one place in a deseralization function in ethportal-api. I don't understand how that would be spaghetti, when it is contained and defined for detecting which historical format of the JSON-RPC the client is using.

I don't want the deserilize block code to be
```
fn deserialize(client_type, block_height, serialized_data) {
 match client_type {
   geth => {
     if block_height > 120000 {
     // xyz
   } else if block_height > 5000 {
     //abc
  } else {
  // adc
}  
}
}
```

I don't think the deseralization function should require the block height, but if we are doing this by detecting clients we will also have to provide block height. How are we getting this block height? Why are we passing it around the whole codebase?

If we don't provide blockheight then it is just what I am proposing anyways and there isn't a need to provide the client_type, providing a client_type would just be extra steps.

My method would look like assuming we are deserializing receipts
```
fn deserialize(serialized_data) {
 if seralized data contains field only in byzantium {
   // abc
 } else {
   //bca
 }
}
}
```

There are defined shifts which changed the JSON-RPC.

The changes in JSON-RPC we are talking about is

If the client provides time accurate JSON-RPC
or if it provides all JSON-RPC requests formatted in the latest format retroactively.

I don't get why we would need to know a client type to figure out this. Or how this is ``spaghetti code``. Detecting client_type provides un-needed complexity to a defined problem imho.

**Comment by njgheorghita** [comment]
This has been completed with/ support for infura & local clients in the bridge: #1089

**Comment by pipermerriam** [comment]
Who's gonna write up a blog post on how people can run their own bridges?

**Comment by KolbyML** [comment]
I will do it 👍
