### ISSUE TITLE
web3_http_address should replace web3_http_port in TrinConfig

### ISSUE THREAD

**Issue by mrferris** [ethereum/trin#129]
From #127:

@njgheorghita:
> In order to communicate to our http server from outside of a docker container, we need to bind to 0.0.0.0 rather than 127.0.0.1. Though, I'm not sure if this opens up some security vulnerabilities as the new default? And instead should be controlled via cli flag / env var?

@lithp:
> The long-term solution is probably to turn web3_http_port into web3_http_addr, and default to localhost. Right now this [hardcoding `0.0.0.0` instead of allowing the entire ip + port be configurable] is technically insecure because it defaults to turning any trin vulnerability into a vulnerability on a public open port.

**Comment by lithp** [comment]
@bhunter7 Sorry to hear that you have lost some of your Ethereum, it sounds like it might have been stolen from you. Unfortunately, we have no way of helping you, this repository is the wrong place to ask for help.

**Comment by bhunter7** [comment]
How did you lose part?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bhunter7** [comment]
Where do I look if you can’t help?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bhunter7** [comment]
You’re not givining me enough information to even locate who to talk to

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bhunter7** [comment]
Please answer mw

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bhunter7** [comment]
Please answer me

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bhunter7** [comment]
Are you the person I need to talk to

**Comment by bhunter7** [comment]
My email is outlook. I keep it updated but I kept the hotmail because I have had it for many years. Thank I’d bhunter7 and.it was my Ethereum that part of it was stolen Could you please tell me what is going on?

**Comment by mrferris** [comment]
@bhunter7 Github is not the place to be asking this, and we are not the people to ask. We write the code but we are not administrators because Ethereum does not have administrators. I would ask for help tracking your Ether on either reddit.com/r/ethereum or reddit.com/r/ethereumnoobies. I would also make sure that you spend time wording what happened properly, because your descriptions above are difficult to follow. 

Also, do know in advance that Ethereum transactions are not reversible, so your best bet is likely to learn from this and not answer strange emails or send Ether to people you don't know.

**Comment by bhunter7** [comment]
If you’re the person I talked to on GitHub  and you were not answering me, that made it worse and so I had to find out what happened myself. I’m not going to just take it and learn from it but the ones involved maybe will. The coin wasn’t in my possession and if your trying to blame me by telling me not to answer strange emails yours IDs the only strange one whose emailed me. No one but myself and Coinbase knew my Ethereum was staked. I wasn’t getting any answers about what chain it was on until a girl from GitHub reached out to me. I’ll be sure to forward all emails with screenshots of the conversations that I found. I wouldn’t had to do that if you weren’t being evasive. The fault lays at your feet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bhunter7** [comment]
You also began the first time you emailed me that part was missing and then it was stolen Don me.  Then now you’re trying to cover yourself and what others have said by saying be careful who I send it to and trying to make it my fault. You’re right I should be careful who Coinbase sent it to because it was you and a few more.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bhunter7** [comment]
Could you please tell me what you found out. I have emails and screenshots but I want to know what you found out. I have an Ethereum 2 in my account and I don’t know If they added back the $500 that was taken out before staking? I’m still losing on this I’m not earning the 5% for staking and I can’t do anything with Ethereum 2 to make any money with it. It seems they should pay the 5% till we can use the new Eth. and thefy mentioned coins for staking when it was done. I am appreciative of getting Ethereum 2 because it would have been wrong not too. I paid over $3,900 for it. The guy who emailed me and was one of the ones supposed to be working with my Ethereum first I was told pat of it was missing and he changed that and said it was stolen and it was my fault and I should just accept it. Then he went on to tell me what I shouldn’t have done and none of that was true. He was threatening me basically and I feel he should not be working with people’s valuable coins. He just didn’t seem like a very principled or honest person and I wouldn’t be surprised if someone else looses their coin if they haven’t already. Please figure out what happened before someone this happens to someone else. Thank you and I would appreciate it if you would get back with me.
Blessings,
Belinda Hunter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by carver** [comment]
@bhunter7 We cannot provide any further help. It sounds like you've got a frustrating situation, and one that you don't fully understand.

None of us have the responsibility or capability to send you any Ethereum-based assets that you have sent away or lost.

We love to help in whatever small way that we can. We suggested other places to ask for help, but that seems to have been ignored.

To reiterate the most important lesson: do *not* trust people's claims about who they are, or what they will do with your assets. That's especially important when someone contacts you (rather than you contacting them). Note that you found real Ethereum developers by contacting us. Whoever initiated the conversation with you must be a scammer (and is not an actual Ethereum developer).

We wish you the best of luck in the future and are sorry for your loss.

This thread is now locked, as off-topic.
