### ISSUE TITLE
Robust RecursiveFindContent | Continue the search if data transfer fails

### ISSUE THREAD

**Issue by KolbyML** [ethereum/trin#1383]
![image](https://github.com/user-attachments/assets/3cad4cff-debd-47e7-9ddf-cd76ac7a939c)

Clients can have bugs, trin has had bugs, shisui has, ultralight etc. A bug in a client shouldn't stop the whole show. A bug we were seeing was trin found the content from a shisui or trin node, then the uTP transfer would fail for some unknown reason, then we would just return an error.

Instead of this we could continue the search until we find a working peer, we already did a big search to find the contents neighbourhood so it isn't out of question if the first node we try to get the data from fails, we just try another and continue the search to some failure level till we either fail X times and give up or successfully fetch the data.

**Comment by morph-dev** [comment]
@carver if I understood correctly, you said you are looking into this or something similar, right? Maybe you can add your progress or assign it to yourself if that's the case

**Comment by carver** [comment]
Tracking To-dos before this is complete:
- [ ] #1395 
- [ ]  send update to query when validation fails, so that it can reduce the tracker of num_validations & pursue content from other peers
- [ ] test that content can still be found, when the first one to transmit fails (might look like adding a chance of not validating to the `termination_and_parallelism` loop)

Probably move to a follow-up issue:
- [ ] increase parallel to 2
- [ ] add a timeout, in case validation takes too long
- [ ] Add QueryTrace features: 1) measure time to validate (currently would include uTP transfer), 2) mark if a peer sent us invalid data
- [ ] Further split the query stages, so we can trace the difference between: A) utp download failed and B) download succeeded / validation failed. Currently they look the same to the trace.
