### ISSUE TITLE
Move content ID derivation and distance computation logic into respective overlay crates

### ISSUE THREAD

**Issue by jacobkaufmann** [ethereum/trin#219]
As discussed in #216, we ought to move content ID derivation and distance computation logic for each overlay protocol into the respective overlay crates. At first thought, these could be closures or functions that operate on byte arrays and hashes, which are passed into the overlay at construction.

**Comment by njgheorghita** [comment]
Just a heads up - #230 touches on this issue - seems to have resolved the content id derivation aspect by using the `ContentKey` type, but hasn't resolved the distance computation aspect. Though I think that can easily enough be solved in the same way using the `ContentKey` type. Not sure if I will address that now or later since the pr is getting large already.

**Comment by njgheorghita** [comment]
closing since we have other open issues tracking state distance calculation
