### ISSUE TITLE
uTP timestamp_microseconds overflow simplification and in-code commentary

### ISSUE THREAD

**Issue by carver** [ethereum/trin#227]
The uTP `PacketHeader.timestamp` is measured in microseconds, truncated to a u32. That means it can only count up to ~4200 seconds before rolling over. This is (potentially) fine,  but I noticed a couple issues:
- Calling that field a timestamp is confusing. It's a reference counter that rolls over every ~hour, which just feels very different from most things called a timestamp. Usually a timestamp can specify many specific datetimes, and only rolls over every 137 years. So maybe we should name it `usec_counter` or something like that.
- Calculating the time difference after a rollover looks wrong to me (in `get_time_diff()`). The difference between the current time (rolled over) and the previous time (before rollover) is not equal to `previous_time - current_time`. Instead, I expect it to be `U32_MAX - previous_time + current_time`.

_Originally posted by @carver in https://github.com/ethereum/trin/pull/84#r787157664_

**Comment by KolbyML** [comment]
https://www.bittorrent.org/beps/bep_0029.html
![image](https://user-images.githubusercontent.com/31669092/150024366-8884d15c-6cbd-4e82-a27f-5f93a4a58569.png)

I don't think we should change the name as it should follow the spec

**Comment by KolbyML** [comment]
In get_time_diff() we take the absolute value of the current and response time. To my understanding, current_time and response_time should never roll over in the first place.

**Comment by carver** [comment]
> I don't think we should change the name as it should follow the spec.

Yup, agreed

> So I can change it to timestamp_microseconds, if you would like

Yeah, `timestamp_microseconds` sounds better, especially after looking at the spec. As I read [`gettimeofday()`](https://man7.org/linux/man-pages/man2/settimeofday.2.html), this value should be *only* the microseconds, not the full timestamp masked to the lowest 32 bits. It should always be in the range `[0, 999999]`, rolling over to 0 at every second.

**Comment by KolbyML** [comment]
>  As I read [`gettimeofday()`](https://man7.org/linux/man-pages/man2/settimeofday.2.html), this value should be _only_ the microseconds, not the full timestamp masked to the lowest 32 bits. It should always be in the range `[0, 999999]`, rolling over to 0 at every second.

https://github.com/bittorrent/libutp

This is the reference implementation. utp_utils.cpp is where the UTP_GetMicroseconds() function is implemented which is the same idea as get_time() in the Rust implementation. 

I ran it just to make sure my eyes weren't deceiving me

![image](https://user-images.githubusercontent.com/31669092/150077280-759b9742-77af-4d64-b089-5eb090a90e33.png)

So evidently ``range [0, 999999]`` isn't actually being a thing. It doesn't even use gettimeofday() in the UNIX implementation (I am on Windows). This could probably be a case of spec lacking behind reference implementation, which Konrads had noted going through the standard implementation well implementing the Nim implementation.

![image](https://user-images.githubusercontent.com/31669092/150078587-31cc4034-5cc5-4418-8e94-4716561b6b89.png)

The bitwise operation isn't even needed because u32 will do it automatically from shown above.

``u128::MAX as u32`` will convert u128::MAX to u32::MAX

Anyways if you have any other concerns let me know and I can answer them for you. I probably should start studying now.

**Comment by ogenev** [comment]
I guess this downcasting from `u64` UNIX timestamp in microseconds to `u32` is just for optimization purposes because we care only for the lower bits of the number, disregarding the upper bits?

**Comment by carver** [comment]
> In get_time_diff() we take the absolute value of the current and response time. To my understanding, current_time and response_time should never result in a rollover in the first place.

Yes I agree that the current approach never creates a rollover. But I don't think it produces the desired value. In trying to calculate the delay between peers, we are measuring the difference in time from sending to receiving.

```

1s        2s         3s
 ____________________
|_________|__________|
        ^    ^
        S    R
```

So if `Sender` (`S`) sends at a local timestamp 0.900001, and therefore includes a timestamp_microseconds of `900001`, and `Receiver` (`R`) receives at a local timestamp of 1.150002, with a current microseconds time of `150002`, then I would expect the `timestamp_difference_microseconds` to be `250001` (the time elapsed, ignoring clock skew) instead of `749999` (what `get_time_diff()` returns).

So I think `get_time_diff()` should have the `if` branch, but in the second path it should do `1000000 - response_time + current_time`. (after `get_time()` is modified to always return in the range `[0, 999999]`)

**Comment by carver** [comment]
Ugh, it's a rough situation to have the key reference implementation so far from the spec. Now we have to have a real conversation about whether we will follow the spec or the reference, or make up some 3rd thing that we like better. All of them are legitimate options, which means it won't be fast, to do it well.

Whelp, so far I'm unimpressed by the complete lack of rollover handling in usages of `utp_call_get_microseconds()` in https://github.com/bittorrent/libutp/blob/2b364cbb0650bdab64a5de2abb4518f9f228ec44/utp_internal.cpp

It seems like the code typically just YOLO casts to u32. Yeesh.

**Comment by KolbyML** [comment]
> ```
> 
> 1s        2s         3s
>  ____________________
> |_________|__________|
>         ^    ^
>         S    R
> ```
> 
> So if `Sender` (`S`) sends at a local timestamp 0.900001, and therefore includes a timestamp_microseconds of `900001`, and `Receiver` (`R`) receives at a local timestamp of 1.150002, with a current microseconds time of `150002`, then I would expect the `timestamp_difference_microseconds` to be `250001` (the time elapsed, ignoring clock skew) instead of `749999` (what `get_time_diff()` returns).
> 
> So I think `get_time_diff()` should have the `if` branch, but in the second path it should do `1000000 - response_time + current_time`. (after `get_time()` is modified to always return in the range `[0, 999999]`)

![image](https://user-images.githubusercontent.com/31669092/150260851-4d71afa6-3b88-496f-b043-5fcc3cb3bf54.png)
This is how the standard implementation does get_time_diff()

timestamp_microseconds is only used by Ledbat (uTP's congestion protocol). It uses the last 10 timestamp_microseconds /diffs to detect if there is a higher or lower delay than normal and adjusts how fast it sends packets accordingly, to not use all the bandwidth on the network and give TCP connections priority.
!
![image](https://user-images.githubusercontent.com/31669092/150257301-cd62969a-badd-416f-893f-70e748e61bb9.png)
! (page 12 from the Ledbat spec just to get an idea) https://datatracker.ietf.org/doc/html/rfc6817

uTP is a pretty simple spec because it assumes you already have an understanding of TCP, Ledbat spec goes a lot more in-depth. 

Anyways so the actual timestamp doesn't matter that much (PC1) can have a time of 50000 and (PC2) can have one of 20000. We just want to know if there is a swing in this delay, which would mean there is traffic on a TCP stream we should give priority to.

**Comment by ogenev** [comment]
It seems that when we calculate the timestamp difference in microseconds, most of the time this is true:

```rust
assert_eq!(unix_timestamp_microseconds_2 - unix_timestamp_microseconds_1, unix_timestamp_microseconds_2 as u32 - unix_timestamp_microseconds_1 as u32)
```

As pointed out in Nim's [implementation](https://github.com/status-im/nim-eth/blob/26ab9b078e610b0eb685e8d98a1f34d9bfabb053/eth/utp/packets.nim#L71) sometimes this may lead to sudden spikes in calculated delays but it should be not a problem because Ledbat uses the min of the last 10 timestamp diffs.

**Comment by KolbyML** [comment]
observation window values (last 10?).

Yes it uses the last 10.

**Comment by carver** [comment]
Ok, using the minimum of the last 10 observations, and this happening ~1x/hr is a good enough reason in my book to just run the subtraction and let it overflow. But it deserves a comment where the overflows can happen, explaining the rationale. (and maybe linking to this issue?)

**Comment by carver** [comment]
This seems like a solid template for the kind of comment that would be great to see in the code:
https://github.com/status-im/nim-eth/blob/cf95b688e647e52bd8dd937926d20257b564fe43/eth/utp/packets.nim#L71-L77
```
  # Casting this value from int64 to uin32, my lead to some sudden spikes in
  # timestamp numeric values i.e it is possible that timestamp can suddenly change
  # from 4294967296 to for example 10, this may lead to sudden spikes in
  # calculated delays
  # uTP implementation is resistant to those spikes are as it keeps history of
  # few last delays on uses smallest one for calculating ledbat window.
  # so any outlier huge value will be ignored
```

**Comment by ogenev** [comment]
Closing this as it is not relevant anymore.
