### ISSUE TITLE
Use `u256` for data radius in portal storage and set the default radius value to `u256::MAX`

### ISSUE THREAD

**Issue by ogenev** [ethereum/trin#350]
There are some confusing discrepancies in implementing the data radius in our codebase.

Data radius is defined as a `U256` value in the portal network[ specs](https://github.com/ethereum/portal-network-specs/blob/master/history-network.md#radius) but in portal storage, we use `u64`: 

https://github.com/ethereum/trin/blob/43c2527c7f941a015b9d7b322f1a139fcf9a53c0/trin-core/src/portalnet/storage.rs#L41

https://github.com/ethereum/trin/blob/43c2527c7f941a015b9d7b322f1a139fcf9a53c0/trin-core/src/portalnet/storage.rs#L217

https://github.com/ethereum/trin/blob/43c2527c7f941a015b9d7b322f1a139fcf9a53c0/trin-core/src/portalnet/storage.rs#L132

We need to change the portal storage radius type to `u256` and set the default data radius to `u256::MAX` instead of `u64::MAX` so we can cover the entire key space, which is `U256::MAX`:

https://github.com/ethereum/trin/blob/43c2527c7f941a015b9d7b322f1a139fcf9a53c0/ethportal-peertest/src/jsonrpc.rs#L20

https://github.com/ethereum/trin/blob/43c2527c7f941a015b9d7b322f1a139fcf9a53c0/trin-core/src/portalnet/overlay_service.rs#L394

https://github.com/ethereum/trin/blob/43c2527c7f941a015b9d7b322f1a139fcf9a53c0/trin-core/src/portalnet/overlay_service.rs#L1039

**Comment by mrferris** [comment]
I think that PR #305 does some of this.

Also note that internally to Portal Storage we decided to use a u64 to make distance calculations simpler. We use SQLite queries to find the farthest content id in the DB, and SQLite doesn't support U256 numbers. So we just use a u64 to represent the most significant 8 bytes of a U256. The less-significant bytes end up being noise anyway.

The problem with `PortalStorage` is that it looks like it's setup to have the `u64` read directly by whatever's using it, whereas it should have a `get_radius() -> U256` method that pads that u64 in order to return a U256.

**Comment by jacobkaufmann** [comment]
Closing based on merge of #305
