### ISSUE TITLE
Remove `win-build` CI step

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#379]
See discussion [here](https://github.com/ethereum/trin/pull/378).

### Why?
- This CI step takes an extraordinary amount of time (typically > 30mins)
- No active developers use a windows machine, the initial reason we introduced this ci step
- We can easily reintroduce windows support if it's deemed desirable as we approach some kind of stable release

**Comment by mrferris** [comment]
Does @carver use windows?

**Comment by carver** [comment]
As irritating as it is, I think Windows support should be a Beta goal, because it's still used so broadly. (Based on the last time that I saw etherscan's browser-agent stats, anyway)

I'm 👍🏻 for quieting the windows CI step with ignore checksum for now, and sligthly 👎🏻 on removing it from CI entirely, because I think we'll just need to re-add it again soon.

**Comment by njgheorghita** [comment]
Closing since this is now tracked in #318
