### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'attempt to multiply with overflow'

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trin#438]
I get a lot of these when running the `eth-portal` bridge client:

```
thread 'tokio-runtime-worker' panicked at 'attempt to multiply with overflow', trin-core/src/utp/stream.rs:849:9
```

Unclear if this is trin <> trin or cross client behavior.

**Comment by ogenev** [comment]
> I could fix this and refactor the utp stream implementation to use `tokio::time::Duration` across the board, instead of the current somewhat bespoke implementation. @ogenev objections? :) 

No objections, feel free to open a PR with anything you feel suitable. A lot of things can be improved in utp 😄

**Comment by njgheorghita** [comment]
@erwanor Any progress on this? I'm still seeing a lot of these errors occurring. If not, no worries at all, we have plenty of other issues to tackle, hahaha. And in the meantime, maybe @ogenev can knock this one out

**Comment by ogenev** [comment]
> I'm still seeing a lot of these errors occurring.

Just curious, do you use the latest master (with the FindContent uTP fix)?

**Comment by njgheorghita** [comment]
@ogenev Yup, it's still occurring on the latest master for me, also seeing a lot of `WARN trin_core::utp::stream: Received STATE packet for an unknown active uTP stream: Packet {}` errors

**Comment by njgheorghita** [comment]
Admittedly, I'm not intimately familiar with the utp spec, but it seems like this could be the source of the issue?
https://github.com/ethereum/trin/blob/master/trin-core/src/utp/stream.rs#L878

As it stands now, the congestion time is squared every time this method is hit, causing it to rise exponentially and eventually overflowing the multiplication buffer. Is it supposed to be squared every time? Or should it just be doubled?

**Comment by ogenev** [comment]
> As it stands now, the congestion time is squared every time this method is hit, causing it to rise exponentially and eventually overflowing the multiplication buffer. Maybe it would be better to simply increment it with a constant value - like the `MIN_CONGESTION_TIMEOUT`?

Yes, incrementing with `MIN_CONGESTION_TIMEOUT` and [saturating_add](https://doc.rust-lang.org/std/primitive.u32.html#method.saturating_add) should solve the overflow panic which is the quickest fix.

However, why is this method called multiple times in a row?

We call this method every time we send a uTP packet and don't receive a response from the remote socket. This is part of the resend uTP logic which works as follows:

1. We send uTP packet.
2. We listen on the uTP socket for a response.
3. If we don't get a response by a set time of a timeout, we resend the uTP packet.

The problem is that we don't have a resend limit, for example, Fluffy tries to resend a packet 4 times and then gives up but we keep resending the packet forever :face_exhaling:. 

So a more fundamental fix to the problem would be to implement a resend limit on lost uTP packets.
