### ISSUE TITLE
Enable `clippy::cargo` and/or `unused_crate_dependencies` lints for every workspace

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#599]
As the title says, it would be nice to have these lints enabled for every workspace
more context : https://github.com/ethereum/trin/pull/575#discussion_r1140504504

[UNUSED_CRATE_DEPENDENCIES](https://doc.rust-lang.org/beta/nightly-rustc/rustc_lint_defs/builtin/static.UNUSED_CRATE_DEPENDENCIES.html) seems to have some peculiar edge cases

**Comment by e3243eric** [comment]
I tried to enable `clippy::cargo` or `unused_crate_dependencies` for all workspaces. But in some cases, both linters have false positives, and this cause a bunch of lint errors in Trin.

- `clippy::cargo`
  - [multiple_crate_versions](https://rust-lang.github.io/rust-clippy/stable/index.html#multiple_crate_versions) is one of lint in `clippy::cargo`. It has a known issue for errors caused by the dependencies themselves.
  - Like in Trin, `reth-primitives` has a dependency on `hashbrown@0.13.2`, but `eth_trie` has a dependency on `hashbrown @0.3.1`, then the lint will issue `multiple versions for dependency hashbrown`.
  - Related [Issue#9756](https://github.com/rust-lang/rust-clippy/issues/9756) on clippy.
- [`unused_crate_dependencies`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_lint_defs/builtin/static.UNUSED_CRATE_DEPENDENCIES.html)
  - As docs said, it has a known issue for multiple create in a cargo package.
  - Like in the Trin package (trin/src), the package has a dependency on `anyhow`. `anyhow` is used in `bin/purge_db.rs` but not in `lib.rs`, then the linter will incorrectly issue `anyhow` is unused in the `lib.rs`.
  - Related [Issue#95513](https://github.com/rust-lang/rust/issues/95513) on rust.

**Comment by njgheorghita** [comment]
@e3243eric Thanks for looking into this! Yeah, I've played around with these and was never able to find a stable configuration, I ran into a lot of the errors you're describing. So it's nice to get some confirmation. I wasn't aware of the `multiple_crate_versions` lint, and it would be so nice to get something like that in...

If I have a pr in which I suspect that there are some unused crate dependencies, what I'll do is plug in `#[warn(unused_crate_dependencies)]` lint in the `lib.rs` of the specific workspace. Then I'll run the linter locally. And it's usually pretty good about telling me if there are any unused dependencies. Of course, there are also some false positives, but I just ignore those. 

My question is... do you have any ideas / could you look into an "optional" lint configuration? In an ideal world, it would be a lint I would run locally (probably just before merging a pr), but it wouldn't be included in our ci build (so we don't have to worry about the issues breaking the build). This "optional" lint configuration would lint for `unused_crate_dependencies` & `multiple_crate_version`. Tbh, I'm not so concerned about verify the `clippy::cargo` lint, but if it can be included as well, that would be nice.

Honestly, it might even be best to just add a command to the `Makefile` that will lint specifically for the above mentioned lints. Then this is something that could easily be run locally and wouldn't affect our ci builds
