### ISSUE TITLE
Fix trin deployment in ethereum/cluster

### ISSUE THREAD

**Issue by carver** [ethereum/trin#842]
Two things:
- [x] the bridge is missing an argument
- [x] the database purge gets stuck (and we probably don't want to do it anymore anyway)

**Comment by njgheorghita** [comment]
@carver just curious as to this statement: `the database purge gets stuck (and we probably don't want to do it anymore anyway`. Why? I think it's probably something we do want to continue to do. Although, if we're not careful (eg. keeping it up to date with beacon & state network content keys/values) it could end up deleting a lot of valid info.

Or maybe it's something we'll want to run periodically rather than on every network deployment. Like every quarter or something, make sure the script is up to date with all supported content types, and then run it against every network node?
