### ISSUE TITLE
Redesign the Dockerfiles for faster deployments

### ISSUE THREAD

**Issue by carver** [ethereum/trin#852]
It seems that we are re-copying the accumulator data on every docker version rebuild, which requires a huge download at deploy time.

Fixing this is probably as straightforward as moving the accumulator data copy before any steps that change in a data release (like the code build steps).

Same issue happens with both Dockerfiles I believe, in https://github.com/ethereum/trin/tree/7ab829a74fdd1c03d122ad19aee513fc76817aa3/docker

**Comment by Perelyn-sama** [comment]
Please assign this to me

**Comment by njgheorghita** [comment]
@Perelyn-sama Typically in this repository, we aren't "strict" advocates of the "Assignee" github feature. Especially in the open-source world, it is frequent that an outside contributor wants to contribute, and then disappears after being assigned the task. 

But, at the same time, it's important that other contributors know you're working on an issue so that we don't duplicate work. 

So, if there's an issue that you'd like to take on, it's sufficient to just leave a comment on the issue that you're going to be working on resolving the issue.

**Comment by Perelyn-sama** [comment]
That sounds reasonable. Thank you for the clarification. @njgheorghita

**Comment by njgheorghita** [comment]
fixed in #1164
