### ISSUE TITLE
Strategy for handling CLI arguments for selecting subnetworks.

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#90]
This issue is to track the discussion about the ideal way to structure cli arguments. Basically....
`cargo run --networks history,gossip` or `cargo run --history --gossip`

Some thoughts to consider...
- Different subnets require different arguments. 
  - This is just an example, but it's probably safe to assume there might end up being a fair amount of cli options for trin and its subnets..
    - `cargo run --networks history,gossip --history-udp 8086 --gossip-udp 8087 ...`
    - `cargo run --history --history-udp 8086 --gossip --gossip-udp 8087 --max-gossip-db-size 1gb ...`
  - This raises the question that at some point, we'll probably want to support (and encourage) the use of a config file to set the different params to avoid cli arg congestion
- What are our expectations for the average end-users understanding of trin's internals? How much custom configuration are they expected to want control over. What are the **realistic** use cases where an end user would only want to run a single (or subset of) subnet(s)?

**Comment by victor-wei126** [comment]
I think the first option is clearer, at least to me, that we are running two separate networks, history and gossip, instead of just having `--history`. Regarding custom configs, I would say cache would probably be a good one to give users optional control over, since trin is supposed to be running on lightweight devices.

I have no idea why someone would want to run a single subnet, since then the client can't function as a wallet. The only thing I can think of is if someone just wants to track the balance of some contract, or some account they are interested in, they could just run the state network.

**Comment by ogenev** [comment]
On the implementation side, StructOpt supports[ subcommands](https://docs.rs/structopt/0.3.23/structopt/#subcommands) which may be the perfect fit to handle network subcommands, something like:

`cargo run --networks history,gossip --history --udp 8086 --gossip --udp 8087 `
